######################################################################
# Automatically generated by qmake (1.04a) Mon Jan 5 16:38:36 2004
######################################################################

target.path = /usr/local/bin


TEMPLATE = app
INCLUDEPATH += .

# Input
HEADERS = form.h keycode.h savetypes.h sendevent.h flash.h
SOURCES = form.cpp keycode.cpp main.cpp savetypes.cpp sendevent.cpp flash.cpp
CONFIG += qt

INSTALLS += target
